version: "3.9"
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  app:
    container_name: link-shortener-spring
    image: link-shortener-spring
    env_file:
      - app.env
    ports:
      - "8090:8090"
    depends_on:
      - redis


volumes:
  redis:
    driver: local