version: "3.9"
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis:/data
  app:
    container_name: link-shortener-spring
    image: link-shortener-spring
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - redis


volumes:
  redis:
    driver: local