version: "3.7"

services:
  runner:
    image: tcardonne/github-runner:latest
    environment:
      RUNNER_NAME: "github-actions-runner"
      RUNNER_REPOSITORY_URL: "https://github.com/qnocks/link-shortener"
      RUNNER_TOKEN: "${TOKEN}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock