server:
  address: ${SERVER_HOST}
  port: ${SERVER_PORT}
  error:
    include-message: always
    include-stacktrace: on_param

spring:
  config:
    import: file:env.properties
  application:
    name: link-shortener
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASS}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /swagger-ui.html
